# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
vec=np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
vector1 = np.arange(10, 49)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [4]:
print(vector1.shape)

(39,)


5. Print the type of the previous array in question 3

In [5]:
print(vector1.dtype)

int32


6. Print the numpy version and the configuration


In [6]:
print(np.__version__, np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kashif Alam/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Kashif Alam/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kashif Alam/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\wi

7. Print the dimension of the array in question 3


In [7]:
print(vector1.ndim)

1


8. Create a boolean array with all the True values

In [8]:
vector2=np.array(range(1,10), dtype="bool")
print(vector2)

[ True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
vec=np.zeros((2,2))
print(vec)

[[0. 0.]
 [0. 0.]]


10. Create a three dimensional array



In [10]:
vec=np.zeros((3,3))
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
reverse_vector = np.array(range(1, 10))
print("Original: ", reverse_vector)

reverse_vector[0], reverse_vector[len(reverse_vector) - 1] = reverse_vector[len(reverse_vector) - 1], reverse_vector[0]

print("Modified: ", reverse_vector)

Original:  [1 2 3 4 5 6 7 8 9]
Modified:  [9 2 3 4 5 6 7 8 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null_vector = np.zeros(10)
print(null_vector)
null_vector[5]=1 
print(null_vector) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
matrix=np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr=arr.astype(np.float32)
print(arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

print(np.multiply(arr1,arr2))

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],      [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],      [7., 2., 12.]])
print(np.greater(arr1,arr2))

[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(9)
filtered_array = filter(lambda val: val % 2 == 0, arr)
list(filtered_array)

[0, 2, 4, 6, 8]

18. Replace all odd numbers to -1 from previous array

In [18]:
arr[arr % 2 == 0] = -1
print(arr)


[-1  1 -1  3 -1  5 -1  7 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
print(arr)
arr[5] = arr[6] = arr[7] = arr[8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:

arr = np.ones((8, 8))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

               [4, 5, 6], 

                    [7, 8, 9]])
arr2d[1, 1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12] ] ])

arr3d[0][:] = 64
arr3d[1][:] = 64

print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[64 64 64]
  [64 64 64]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr = np.arange(9).reshape(3, 3)
arr2 = arr[0] #TODO
print(arr2)

[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr = np.arange(9).reshape(3, 3)
val = arr[1][1] #TODO
print(val)


4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr = np.arange(9).reshape(3, 3)
arr3 = arr[0:-1, -1]

print(arr3)

[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr = np.arange(100).reshape(10, 10)
maxInColumns = np.amax(arr, axis=1)
val = max(maxInColumns)
print(val)

99


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
# data = np.random.randn(7,4) # --> This gives floating point numbers
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where(name[data] != "Will"))

[4]
(array([], dtype=int64),)


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
# data = np.random.randn(7,4) # --> This gives floating point numbers
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where((name[data] != "Joe") & (name[data] != "Will")))

print("Difficulty Level Hard")

[2 5 3 4 0]
(array([2, 4], dtype=int64),)
Difficulty Level Hard


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr = np.random.uniform(low=1.0, high=15.0, size=(5,3))
print(arr)


[[10.48457383 12.95545979  4.43536157]
 [14.77440528  3.77979394 13.01986545]
 [ 7.52990199  5.01508221  5.94243245]
 [14.97068972 10.23582634  1.04504714]
 [10.82792696 11.2152142  10.82480372]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr_klo = np.random.uniform(low=1.0, high=16.0, size=(2,2,4))
print(arr_klo)

[[[14.8428051   1.00454591 10.59493861  8.32255919]
  [12.85161769  5.04131508 13.73030422 15.36926534]]

 [[ 3.15192888  2.38269552 10.70701366 12.72901899]
  [12.64070122 14.20665432 13.48612465  7.95886827]]]


33. Swap axes of the array you created in Question 32

In [33]:

np.swapaxes(arr_klo, 0, 1)
print(arr_klo)


[[[14.8428051   1.00454591 10.59493861  8.32255919]
  [12.85161769  5.04131508 13.73030422 15.36926534]]

 [[ 3.15192888  2.38269552 10.70701366 12.72901899]
  [12.64070122 14.20665432 13.48612465  7.95886827]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
import math

arr = np.arange(10)
print(arr)
new_arr = filter(lambda x: x if math.sqrt(x) > 0.5 else 0, arr)
print(np.asarray(list(new_arr)))



[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [36]:
arr1 = np.random.randint(12, size=random.randrange(0, 12))
arr2 = np.random.randint(12, size=random.randrange(0, 12))
print(arr1)
print(arr2)
print(np.where(arr1 == arr2))

[ 0  7  0 11  6]
[7 0]
(array([], dtype=int64),)


C:\Users\Kashif Alam\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [37]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names)) 

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [38]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)

a = filter(lambda x: x if x not in val else None, a)
print(np.asarray(list(a)))

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [39]:

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray[:, 1] = 10
print(sampleArray)



[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [40]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

a=np.dot(x, y)

print(a)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [41]:
matrix = np.random.randint(20, size=(random.randint(0, 5), random.randint(0, 5)))
b = np.cumsum(matrix)
print (b)

[ 5 10 26 33]
